Test commit
Drozdnik/FamilyFlow pull request #14
Opened 2024-12-29 22:12 UTC by tzopiz

2024-12-29 22:27 UTC, Drozdnik requested changes

2024-12-29 22:27 UTC, Drozdnik commented on .swiftlint.yml
> + - force_unwrapping
давай уберем все с форсом, мы мудаки если напишем просто так

2024-12-29 22:27 UTC, Drozdnik commented on .swiftlint.yml
> + - force_unwrapping
а если реально понадобиться или чтобы протестить гипотезу

2024-12-29 22:27 UTC, Drozdnik commented on .swiftlint.yml
> + - todo
мб тоже оставим?

2024-12-29 22:27 UTC, Drozdnik commented on .swiftlint.yml
> + - unused_enumerated
давай все unused уберем так же для проверки идеи, если что Xcode подскажет

2024-12-29 22:27 UTC, Drozdnik commented on .swiftlint.yml
> + - toggle_bool
за что?(

2024-12-29 22:49 UTC, tzopiz commented on .swiftlint.yml
> + - force_unwrapping
ок

2024-12-29 22:49 UTC, tzopiz commented on .swiftlint.yml
> + - todo
Оставим или уберем?)

2024-12-29 22:49 UTC, tzopiz commented on .swiftlint.yml
> + - unused_enumerated
Это все не ошибки, а ворнинги. Можешь проверять сколько влезет. Xcode не подсказывает, когда допустим у тебя параметр функции не используется. 
Я бы предложил все таки пока оставить как есть - потом, когда столкнемся, что это действительно только мешает сможем пулом на 1 строчку залить

2024-12-29 22:53 UTC, tzopiz commented on .swiftlint.yml
> + - unused_enumerated
В планах разобраться как работают и настроить пре комит и пре пуш хуки и скрипт туда перенести. Потому что дальше, на каждое твое нажатие cmd b скрипт будет пробигаться по всем файлам и смотреть надо ли там что то поменять - звучит не круто(

2024-12-30 09:20 UTC, Drozdnik approved these changes

2024-12-30 14:04 UTC, merged